### ISSUE TITLE
Twig_Error_Runtime

### ISSUE THREAD

**Issue by FDiskas** [Sommerregen/grav-theme-developer#1]
```
An exception has been thrown during the rendering of a template ("Array to string conversion") in "partials/themes-details.html.twig" at line 72.
```

**Comment by Sommerregen** [comment]
Hi @FDiskas although [your fix](https://github.com/Sommerregen/grav-theme-developer/pull/2/files#diff-6e8a91cf3c86487ebf18fc4b6a5233f5R11) may work, I don't think it is appropriate here to use. The reason is semantics. Keywords should be an array not a string.

Thus, your issue is more likely an upstream issue with the [Admin plugin](https://github.com/getgrav/grav-plugin-admin). I actually don't know which version you are using, but browsing through the code seems like you are using an older version. The current version **v1.1.0-beta.5** does it right: It concatenates the array (see https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/partials/themes-details.html.twig#L67).

Can you double check `partials/themes-details.html.twig` with your version of admin plugin?

**Comment by FDiskas** [comment]
I just installed and i hope that there is the latest version. I will check

**Comment by Sommerregen** [comment]
Hi @FDiskas any progress here with your issue? Otherwise I will close this due to inactivity soon.

**Comment by FDiskas** [comment]
Yes I have a installed v1.0.10

**Comment by Sommerregen** [comment]
Just to confirm, is the issue still present or already soled?

Otherwise can you send me a copy of your user folder to test it locally, i.e. share your link with me in Gitter or by sending me an email (sommerregen [at] benjamin-regler [dot] de).
