### ISSUE TITLE
No option to set 'Contact me' email address

### ISSUE THREAD

**Issue by tokelove** [Sommerregen/grav-theme-developer#8]
Hi,

The green button on the top right that says "Contact me" defaults to linking to the site URL. From what I can see there is no config option or page that modifies this.

**Comment by Sommerregen** [comment]
Hi @tokelove ,

as per line [default.html.twig#L75](https://github.com/Sommerregen/grav-theme-developer/blob/develop/templates/default.html.twig#L75) you can set the URL by adding an entry to the `user/configs/themes/developer.yaml`:

```yaml
contact_url: 'your url'
```

Currently, this option is missing in [developer.yaml](https://github.com/Sommerregen/grav-theme-developer/blob/develop/developer.yaml), that's why I mark this issue as enhancement here. Feel free to create a pull request.

All the best,
Sommerregen
